name: Build Node

run-name: ${{ github.actor }} is building/testing node

# Trigger the workflow on pushes and pull requests to the main branch
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Check out the code
      - name: Checkout code
        uses: actions/checkout@v2

      # Set up the environment variable with the GitHub secret
      - name: Set DISCORD_SECRET as environment variable
        run: echo "DISCORD_SECRET=${{ secrets.DISCORD_SECRET }}" >> $GITHUB_ENV

      # Optionally, you can use the secret later in another step
      - name: Use DISCORD_SECRET
        run: |
          echo "The secret is set."
          # You can access the DISCORD_SECRET here like this:
          echo "Secret is $DISCORD_SECRET"
